"""Add score column to User table

Revision ID: a0c62d498c12
Revises: 50f422868168
Create Date: 2024-11-17 01:17:51.345677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c62d498c12'
down_revision = '50f422868168'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('score')

    # ### end Alembic commands ###
